### PR TITLE
20240618/lp

### PR DESCRIPTION
**Pull request by noliver-ykc**
I realize I messed up on the branch title lol

**TO BE:**
Screenshot 2024-06-18 at 20 19 19
**IS NOW BE (lol)**

https://github.com/LCM-Nikki-Nicole/murder_party/assets/74501096/d12ad6f0-c250-4901-8f9f-65a0b997c879

TODO: 
- Update with login page link when its ready
- Figure out how to make it so you can only type in numbers 
- Figure out how to make it so if you press the back button you can erase the previous field and then the one before that and so forth like most tools

### CODE REVIEW

**Comment by noliver-ykc** [comment]
@nrcrls Can you just 動作確認 this to make sure it all works? I wrote the back end code for the code validation and passed it to the front btw

**Comment by noliver-ykc** [comment]
@nrcrls 
i dont think netlify can access other pages within the app unless they are hyperlinked (so just changing the URL doesnt work.... probably) just ignore netlify for now and test it on local pls
and then if its all good pls approve <3

**Comment by nrcrls** [comment]
It's working properly on my local env! Just some notes but they're more suggestions tbh

1. You can change the value of `PUZZLE_CODE` to the actual code so there's no need to define NAZO_CODE. I only put it there to test things and it changing the value to 46890 wouldn't break anything.
2. You can probably move the code in`def validate_code` to `class CodeInputView` so that everything is consistent i.e. class-based instead of function-based. That can be in a different PR or we can just leave it as is huehehe
3. For this code in `server/mystery_party/settings.py`:
```
# might need to update this for netlify later on
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
``` 
you can just change it to
`CORS_ALLOWED_ORIGINS = True`

so it can allow all origins and maybe we won't need to update it for netlify

**Review by nikkicarlos-jpn — APPROVED** [review]
It's working properly on my local env! Just some notes but they're more suggestions tbh

1. You can change the value of `PUZZLE_CODE` to the actual code so there's no need to define NAZO_CODE. I only put it there to test things and it changing the value to 46890 wouldn't break anything.
2. You can probably move the code in`def validate_code` to `class CodeInputView` so that everything is consistent i.e. class-based instead of function-based. That can be in a different PR or we can just leave it as is huehehe
3. For this code in `server/mystery_party/settings.py`:
```
# might need to update this for netlify later on
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
``` 
you can just change it to
`CORS_ALLOWED_ORIGINS = True`

so it can allow all origins and maybe we won't need to update it for netlify

**Comment by noliver-ykc** [comment]
i changed puzzle code but the other fixes caused errors so ill do them on a later PR

**Pull request merged**
